# Site settings
# These are used to personalize your new site.
title: Dylan A. Kelly # your name here
logo: "/images/IMG_1530.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Cybersecurity (class of 2025)
  <br />
  <a href="https://app.joinhandshake.com/stu/users/34099963/">View My Resume</a>
  <br /><br />
repository: "DylanAKelly/dylanakelly/github.io"
github_username:  DylanAKelly # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

